# Generated by Django 5.1.2 on 2024-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='page',
            new_name='pages',
        ),
    ]
